name       : knotes
version    : 21.08.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/knotes-21.08.2.tar.xz : 2925bac240c3c0d660d657fdcb947239ed08f321b6438e13508fc5c5efac79bc
homepage   : https://kde.org/applications/utilities/org.kde.knotes
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdnssd-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kimap-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
