name       : knotes
version    : 19.08.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/knotes-19.08.1.tar.xz : 30b835c063e03d3d9047cbaacf389ee1e261368d2cf73fdfab71b4f9138b8bf7
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - grantlee-devel
    - grantleetheme-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
