name       : knotes
version    : 23.04.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/knotes-23.04.3.tar.xz : ea1b4e14005b555a05ed400267ec5721f5beb1ae967328d2f109242e7c4f4a38
homepage   : https://kde.org/applications/utilities/org.kde.knotes
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdnssd-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kimap-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
