name       : knotes
version    : 20.12.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/knotes-20.12.0.tar.xz : 084ec065435b6a74973396d6bb2322321fad5c81875615e3cdc7272b40ed4e2b
homepage   : https://kde.org/applications/utilities/org.kde.knotes
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - grantlee-devel
    - grantleetheme-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdnssd-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
